Write-Host "Setting environment variables for Terraform"
#$Env:ARM_ACCESS_KEY="xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
#$Env:TF_LOG=""
#$Env:HTTP_PROXY=""
#$Env:HTTPS_PROXY=""
#$Env:ARM_CLIENT_ID="xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
#$Env:ARM_CLIENT_SECRET="your_client_secret"
#$Env:ARM_SUBSCRIPTION_ID="xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
#$Env:ARM_TENANT_ID="xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
#$Env:ARM_ENVIRONMENT="public"
